import {
  Apple,
  Atom,
  Battery,
  Bean,
  Bird,
  Bone,
  BookOpen,
  Bot,
  Brain,
  Bug,
  Calculator,
  Camera,
  Car,
  Carrot,
  CircleHelp,
  Cloud,
  CloudRain,
  Code,
  Cog,
  Compass,
  Cpu,
  Dna,
  Droplet,
  Ear,
  Egg,
  Eye,
  Factory,
  Fish,
  Flame,
  FlaskConical,
  Flower2,
  Gem,
  Glasses,
  Globe,
  Hand,
  Heart,
  Hourglass,
  House,
  Lightbulb,
  Magnet,
  Map,
  Medal,
  Microscope,
  Moon,
  Mountain,
  MountainSnow,
  Music,
  Orbit,
  Palette,
  PawPrint,
  Pencil,
  Plane,
  Plug,
  Puzzle,
  Rainbow,
  Recycle,
  Rocket,
  Ruler,
  Satellite,
  Scale,
  Search,
  Shapes,
  Shield,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Telescope,
  TestTube,
  Thermometer,
  Timer,
  TreePine,
  Trophy,
  Waves,
  Wheat,
  Wifi,
  Wind,
  Zap,
  type LucideIcon,
} from 'lucide-react'

import type { LibraryIconId } from '@/entities/kit'

/** Bundled science icons (content ids → components). Every catalog id must be covered. */
export const LIBRARY_ICON_COMPONENTS = {
  atom: Atom,
  flask: FlaskConical,
  'test-tube': TestTube,
  microscope: Microscope,
  telescope: Telescope,
  magnifier: Search,
  dna: Dna,
  brain: Brain,
  heart: Heart,
  eye: Eye,
  ear: Ear,
  hand: Hand,
  bone: Bone,
  sprout: Sprout,
  leaf: Sprout,
  flower: Flower2,
  tree: TreePine,
  wheat: Wheat,
  carrot: Carrot,
  apple: Apple,
  bean: Bean,
  egg: Egg,
  bug: Bug,
  bird: Bird,
  fish: Fish,
  paw: PawPrint,
  sun: Sun,
  moon: Moon,
  star: Star,
  planet: Orbit,
  rocket: Rocket,
  satellite: Satellite,
  globe: Globe,
  mountain: Mountain,
  volcano: MountainSnow,
  gem: Gem,
  droplet: Droplet,
  waves: Waves,
  cloud: Cloud,
  rain: CloudRain,
  snowflake: Snowflake,
  wind: Wind,
  thermometer: Thermometer,
  flame: Flame,
  rainbow: Rainbow,
  lightbulb: Lightbulb,
  zap: Zap,
  battery: Battery,
  plug: Plug,
  magnet: Magnet,
  cog: Cog,
  robot: Bot,
  cpu: Cpu,
  code: Code,
  wifi: Wifi,
  ruler: Ruler,
  scale: Scale,
  timer: Timer,
  hourglass: Hourglass,
  calculator: Calculator,
  shapes: Shapes,
  puzzle: Puzzle,
  compass: Compass,
  map: Map,
  recycle: Recycle,
  music: Music,
  palette: Palette,
  camera: Camera,
  glasses: Glasses,
  shield: Shield,
  trophy: Trophy,
  medal: Medal,
  book: BookOpen,
  pencil: Pencil,
  question: CircleHelp,
  sparkles: Sparkles,
  house: House,
  factory: Factory,
  car: Car,
  plane: Plane,
} satisfies Record<LibraryIconId, LucideIcon>
