// GENERATED by scripts/sync-edge-entities.mjs from src/entities — do not edit here.
import type { BlockType, Step, StepOf } from '../model/blocks.ts'
import type { CardColor } from '../model/primitives.ts'
import { STATIC_STATE, type VisualKind } from '../model/visual.ts'
import { newItemId } from './ids.ts'

type BlockMeta = {
  label: string
  description: string
  emoji: string
  /** "E-B-M'deki karşılığı" — the reference kit card that used this interaction. */
  referenceHint: string
  /** Visual kinds the block can show; empty = the block has no visual area. */
  visualKinds: readonly VisualKind[]
  visualRequired: boolean
  /** Completion rule shown to editors. */
  completion: string
}

export const BLOCK_CATALOG: Record<BlockType, BlockMeta> = {
  info: {
    label: 'Bilgi kartı',
    description: 'Görsel ve kısa bir açıklama. Görüntülenince tamamlanır.',
    emoji: '💡',
    referenceHint: 'Soru + cevap kartı',
    visualKinds: ['scene', 'ai-scene', 'image', 'video'],
    visualRequired: false,
    completion: 'Kart açılınca',
  },
  'tap-reveal': {
    label: 'Dokun ve keşfet',
    description: 'Çocuk sahneye dokunur, gizli değişim ortaya çıkar.',
    emoji: '👆',
    referenceHint: '“Tohum nedir?” — tohuma dokun, filiz çıksın',
    visualKinds: ['scene', 'ai-scene'],
    visualRequired: true,
    completion: 'İlk dokunuşta',
  },
  'stage-slider': {
    label: 'Evre kaydırıcı',
    description: 'Kaydırıcıyla bir sürecin evreleri arasında gezilir.',
    emoji: '🎚️',
    referenceHint: '“Marul nasıl yetişir?” — 4 evre',
    visualKinds: ['scene', 'ai-scene'],
    visualRequired: true,
    completion: 'Son evreye gelince',
  },
  'explore-hotspots': {
    label: 'Keşif butonları',
    description: 'Her buton sahnede bir öğeyi parlatır ve açıklar.',
    emoji: '🔎',
    referenceHint: '“Sera nedir?” — ışık, su, sıcaklık, hava',
    visualKinds: ['scene', 'ai-scene'],
    visualRequired: true,
    completion: 'Tüm butonlar görülünce',
  },
  'toggle-scene': {
    label: 'Aç / kapat',
    description: 'Bir düğmeyle sahnenin iki hâli arasında geçilir.',
    emoji: '🔆',
    referenceHint: '“Bitkiler neden ışığa ihtiyaç duyar?” — Işığı aç',
    visualKinds: ['scene', 'ai-scene'],
    visualRequired: true,
    completion: 'İlk açışta',
  },
  'animated-scene': {
    label: 'Animasyon',
    description: 'Döngüsel bir animasyon izlenir; durdurulabilir.',
    emoji: '🎞️',
    referenceHint: '“Bitkiler neden suya ihtiyaç duyar?” — su yolculuğu',
    visualKinds: ['scene', 'ai-scene'],
    visualRequired: true,
    completion: 'Kart açılınca',
  },
  'choose-correct': {
    label: 'Doğruları seç',
    description: 'Doğru seçenekler bulununca sahne değişir; yanlışlar esprili uyarır.',
    emoji: '✅',
    referenceHint: '“Tohum çimlenmek için ne ister?” — su, sıcaklık, müzik',
    visualKinds: ['scene', 'ai-scene'],
    visualRequired: true,
    completion: 'Tüm doğrular seçilince',
  },
  'compare-cards': {
    label: 'Karşılaştırma',
    description: 'İki ya da üç kart yan yana; dokununca ayrıntı açılır.',
    emoji: '⚖️',
    referenceHint: '“Tohum ile fide arasındaki fark” — iki kart',
    visualKinds: [],
    visualRequired: false,
    completion: 'Tüm kartlar görülünce',
  },
  quiz: {
    label: 'Quiz',
    description: 'Tek doğru cevaplı soru; açıklama cevaptan sonra gelir.',
    emoji: '❓',
    referenceHint: 'Örnek plandaki quiz bloğu',
    visualKinds: ['scene', 'ai-scene', 'image'],
    visualRequired: false,
    completion: 'Doğru cevapta',
  },
  sequence: {
    label: 'Sıralama',
    description: 'Adımlar doğru sıraya dizilir (dokun-seç-yerleştir).',
    emoji: '🔢',
    referenceHint: 'Örnek plandaki sürükle-bırak bloğu',
    visualKinds: [],
    visualRequired: false,
    completion: 'Sıra doğru olunca',
  },
  matching: {
    label: 'Eşleştirme',
    description: 'Soldakiler sağdakilerle eşleştirilir.',
    emoji: '🔗',
    referenceHint: 'Örnek plandaki eşleştirme oyunu',
    visualKinds: [],
    visualRequired: false,
    completion: 'Tüm eşler bulununca',
  },
  experiment: {
    label: 'Deney',
    description: 'Malzemeler, güvenlik ve sayaçlı adımlarla yönlendirilen deney.',
    emoji: '🧪',
    referenceHint: 'Örnek plandaki deney bloğu',
    visualKinds: [],
    visualRequired: false,
    completion: 'Son adım bitince',
  },
  video: {
    label: 'Video',
    description: 'YouTube ya da MP4 bağlantısıyla video; yükleme yok.',
    emoji: '🎬',
    referenceHint: 'Örnek plandaki video bloğu',
    visualKinds: ['video'],
    visualRequired: true,
    completion: 'MP4’te %80 izlenince, YouTube’da “İzledim” ile',
  },
}

/** Scene states a block drives. AI scenes must provide these plus `static`. */
export function requiredSceneStates(step: Step): string[] {
  switch (step.type) {
    case 'tap-reveal':
      return ['before', 'after']
    case 'toggle-scene':
      return ['off', 'on']
    case 'choose-correct':
      return ['idle', 'success']
    case 'animated-scene':
      return ['play']
    case 'stage-slider':
      return unique(step.stages.map((stage) => stage.state))
    case 'explore-hotspots':
      return unique(['idle', ...step.hotspots.map((hotspot) => hotspot.state)])
    default:
      return []
  }
}

/** Required states + `static`, in display order (for the AI animation panel). */
export function aiSceneStatesFor(step: Step): string[] {
  const states = requiredSceneStates(step)
  return unique([...(states.length ? states : ['play']), STATIC_STATE])
}

function unique(values: string[]) {
  return [...new Set(values)]
}

export type NewStepContext = {
  id: string
  slug: string
  qrCode: string
  cardColor?: CardColor
}

/**
 * Placeholder icons for new sequence items. Deliberately order-free (no digits, no growth
 * stages): the player shows the icons in the shuffled list, so ordered icons would give the
 * answer away. Authors replace them with content emoji.
 */
export const SEQUENCE_ITEM_ICONS = ['🟢', '🟣', '🟠', '🔵', '🟡', '🔴'] as const

/** Placeholder icon for the sequence item at `index` (cycles through SEQUENCE_ITEM_ICONS). */
export function sequenceItemIcon(index: number): string {
  return SEQUENCE_ITEM_ICONS[index % SEQUENCE_ITEM_ICONS.length] ?? SEQUENCE_ITEM_ICONS[0]
}

function base(ctx: NewStepContext, title: string, emoji: string, color: CardColor) {
  return {
    id: ctx.id,
    slug: ctx.slug,
    title,
    icon: { kind: 'emoji' as const, value: emoji },
    cardColor: ctx.cardColor ?? color,
    answer: '',
    narration: '',
    hint: '',
    celebration: '',
    qrCode: ctx.qrCode,
    required: true,
  }
}

type Factories = { [K in BlockType]: (ctx: NewStepContext) => StepOf<K> }

const FACTORIES: Factories = {
  info: (ctx) => ({ ...base(ctx, 'Yeni bilgi kartı', '💡', 'sky'), type: 'info', body: '' }),
  'tap-reveal': (ctx) => ({
    ...base(ctx, 'Dokun ve keşfet', '🌱', 'green'),
    type: 'tap-reveal',
    visual: { kind: 'scene', sceneId: 'seed-sprout' },
    tapLabel: 'Tohuma dokun!',
    revealMessage: 'Filiz çıktı! 🌱',
  }),
  'stage-slider': (ctx) => ({
    ...base(ctx, 'Nasıl büyür?', '🥬', 'lime'),
    type: 'stage-slider',
    visual: { kind: 'scene', sceneId: 'lettuce-growth' },
    stages: [
      { id: newItemId('st'), label: 'Tohum', emoji: '🌰', state: 'seed' },
      { id: newItemId('st'), label: 'Çimlenme', emoji: '🌱', state: 'sprout' },
      { id: newItemId('st'), label: 'Fide', emoji: '🌿', state: 'seedling' },
      { id: newItemId('st'), label: 'Marul', emoji: '🥬', state: 'grown' },
    ],
  }),
  'explore-hotspots': (ctx) => ({
    ...base(ctx, 'Keşfet', '🏡', 'orange'),
    type: 'explore-hotspots',
    visual: { kind: 'scene', sceneId: 'greenhouse' },
    prompt: 'Butonlara dokun, keşfet!',
    hotspots: [
      { id: newItemId('h'), label: 'Işık', icon: '☀️', color: 'yellow', message: '', state: 'sun' },
      { id: newItemId('h'), label: 'Su', icon: '💧', color: 'sky', message: '', state: 'water' },
    ],
  }),
  'toggle-scene': (ctx) => ({
    ...base(ctx, 'Işığı aç', '☀️', 'yellow'),
    type: 'toggle-scene',
    visual: { kind: 'scene', sceneId: 'leaf-kitchen' },
    onLabel: 'Işığı Aç!',
    offLabel: 'Işığı Kapat',
    onMessage: '⭐ Besin pişiyor!',
  }),
  'animated-scene': (ctx) => ({
    ...base(ctx, 'İzle ve öğren', '💧', 'sky'),
    type: 'animated-scene',
    visual: { kind: 'scene', sceneId: 'water-journey' },
    caption: 'Animasyonu izle!',
    staticCaption: 'Animasyon durduruldu. Devam etmek için Oynat’a dokun.',
  }),
  'choose-correct': (ctx) => ({
    ...base(ctx, 'Doğruları bul', '🌡️', 'purple'),
    type: 'choose-correct',
    visual: { kind: 'scene', sceneId: 'germination' },
    prompt: 'Hangileri gerekli?',
    options: [
      { id: newItemId('o'), label: 'Su', icon: '💧', color: 'sky', correct: true, feedback: '' },
      {
        id: newItemId('o'),
        label: 'Sıcaklık',
        icon: '🌡️',
        color: 'orange',
        correct: true,
        feedback: '',
      },
      {
        id: newItemId('o'),
        label: 'Müzik',
        icon: '🎵',
        color: 'purple',
        correct: false,
        feedback: '',
      },
    ],
    successMessage: 'Harika, hepsini buldun!',
  }),
  'compare-cards': (ctx) => ({
    ...base(ctx, 'Farkı bul', '⚖️', 'pink'),
    type: 'compare-cards',
    prompt: 'Kartlara dokun, farkı keşfet!',
    cards: [
      { id: newItemId('c'), title: 'Birinci', icon: '🌰', text: '', detail: '', tone: 'warm' },
      { id: newItemId('c'), title: 'İkinci', icon: '🌿', text: '', detail: '', tone: 'fresh' },
    ],
  }),
  quiz: (ctx) => {
    const options = [
      { id: newItemId('q'), label: '' },
      { id: newItemId('q'), label: '' },
      { id: newItemId('q'), label: '' },
    ]
    return {
      ...base(ctx, 'Soru zamanı', '❓', 'indigo'),
      type: 'quiz',
      question: '',
      options,
      correctOptionId: options[0]?.id ?? '',
      explanation: '',
    }
  },
  sequence: (ctx) => ({
    ...base(ctx, 'Sırala', '🔢', 'sky'),
    type: 'sequence',
    prompt: 'Adımları doğru sıraya diz.',
    items: [
      { id: newItemId('s'), label: '', icon: sequenceItemIcon(0) },
      { id: newItemId('s'), label: '', icon: sequenceItemIcon(1) },
      { id: newItemId('s'), label: '', icon: sequenceItemIcon(2) },
    ],
    successMessage: 'Sıralama doğru!',
  }),
  matching: (ctx) => ({
    ...base(ctx, 'Eşleştir', '🔗', 'lime'),
    type: 'matching',
    prompt: 'Her kartı eşiyle birleştir.',
    pairs: [
      { id: newItemId('p'), left: '', right: '' },
      { id: newItemId('p'), left: '', right: '' },
    ],
    successMessage: 'Tüm eşleri buldun!',
  }),
  experiment: (ctx) => ({
    ...base(ctx, 'Deney zamanı', '🧪', 'purple'),
    type: 'experiment',
    materials: [],
    safety: ['Deneyi bir yetişkinle birlikte yap.'],
    steps: [{ id: newItemId('e'), text: '', timerSec: 0 }],
    observationPrompt: 'Ne gözlemledin?',
  }),
  video: (ctx) => ({
    ...base(ctx, 'Video izle', '🎬', 'pink'),
    type: 'video',
    caption: '',
    questionAfter: '',
  }),
}

export function createDefaultStep<T extends BlockType>(type: T, ctx: NewStepContext): StepOf<T> {
  const factory: (ctx: NewStepContext) => StepOf<T> = FACTORIES[type]
  return factory(ctx)
}
