// GENERATED by scripts/sync-edge-entities.mjs from src/entities — do not edit here.
function channel(value: number) {
  const c = value / 255
  return c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4
}

function parseHex(hex: string): [number, number, number] | null {
  const match = /^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i.exec(hex)
  if (!match) return null
  return [
    Number.parseInt(match[1] ?? '0', 16),
    Number.parseInt(match[2] ?? '0', 16),
    Number.parseInt(match[3] ?? '0', 16),
  ]
}

/** WCAG relative luminance of a `#rrggbb` color. */
export function relativeLuminance(hex: string) {
  const rgb = parseHex(hex)
  if (!rgb) throw new Error(`Invalid hex color: ${hex}`)
  const [r, g, b] = rgb
  return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b)
}

/** WCAG 2.x contrast ratio (1–21). */
export function contrastRatio(foreground: string, background: string) {
  const a = relativeLuminance(foreground)
  const b = relativeLuminance(background)
  const [light, dark] = a > b ? [a, b] : [b, a]
  return (light + 0.05) / (dark + 0.05)
}

/** Kit accent colors carry white text (buttons) → need AA for normal text. */
export const ACCENT_MIN_CONTRAST = 4.5

export function isAccentAccessible(accent: string) {
  return parseHex(accent) !== null && contrastRatio('#ffffff', accent) >= ACCENT_MIN_CONTRAST
}
