// GENERATED by scripts/sync-edge-entities.mjs from src/entities — do not edit here.
const ALPHABET = '0123456789abcdefghijklmnopqrstuvwxyz'

function randomChars(length: number) {
  const bytes = new Uint8Array(length)
  crypto.getRandomValues(bytes)
  let out = ''
  for (const byte of bytes) out += ALPHABET[byte % ALPHABET.length] ?? '0'
  return out
}

/** Card identity (`s-k3j9x2ab`) — stable forever, independent of title and order. */
export function newStepId() {
  return `s-${randomChars(8)}`
}

/** Identity for items inside a block (options, pairs, hotspots …). */
export function newItemId(prefix = 'i') {
  return `${prefix}-${randomChars(6)}`
}

export function newUuid() {
  return crypto.randomUUID()
}
