// GENERATED by scripts/sync-edge-entities.mjs from src/entities — do not edit here.
import type { Step } from '../model/blocks.ts'
import type { KitIcon } from '../model/icons.ts'
import type { KitDocument } from '../model/kit.ts'
import type { MediaRef } from '../model/primitives.ts'
import type { Visual } from '../model/visual.ts'

type RefVisitor = (ref: MediaRef) => MediaRef

function mapIcon(icon: KitIcon, visit: RefVisitor): KitIcon {
  return icon.kind === 'media' ? { kind: 'media', media: visit(icon.media) } : icon
}

function mapVisual<V extends Visual | undefined>(visual: V, visit: RefVisitor): V
function mapVisual(visual: Visual | undefined, visit: RefVisitor): Visual | undefined {
  if (!visual) return visual
  switch (visual.kind) {
    case 'image':
      return { ...visual, media: visit(visual.media) }
    case 'ai-scene':
      return {
        ...visual,
        states: visual.states.map((state) => ({ ...state, media: visit(state.media) })),
      }
    case 'video':
      return visual.source.provider === 'mp4' && visual.source.captions
        ? { ...visual, source: { ...visual.source, captions: visit(visual.source.captions) } }
        : visual
    case 'scene':
      return visual
  }
}

function mapStep(step: Step, visit: RefVisitor): Step {
  const common = {
    icon: mapIcon(step.icon, visit),
    ...(step.audio ? { audio: visit(step.audio) } : {}),
  }
  switch (step.type) {
    case 'video':
      return { ...step, ...common, visual: step.visual ? mapVisual(step.visual, visit) : undefined }
    case 'experiment':
      return {
        ...step,
        ...common,
        steps: step.steps.map((item) =>
          item.image ? { ...item, image: visit(item.image) } : item,
        ),
      }
    case 'compare-cards':
    case 'sequence':
    case 'matching':
      return { ...step, ...common }
    default:
      return { ...step, ...common, visual: mapVisual(step.visual, visit) }
  }
}

/** Walks every media reference in a kit (icons, cover, visuals, audio, captions, images). */
export function mapKitMedia(kit: KitDocument, visit: RefVisitor): KitDocument {
  return {
    ...kit,
    icon: mapIcon(kit.icon, visit),
    ...(kit.cover ? { cover: visit(kit.cover) } : {}),
    steps: kit.steps.map((step) => mapStep(step, visit)),
  }
}

export function collectMediaAssetIds(kit: KitDocument) {
  const ids = new Set<string>()
  mapKitMedia(kit, (ref) => {
    ids.add(ref.assetId)
    return ref
  })
  return ids
}

export type ResolvedAsset = { url: string; alt?: string | undefined }

/**
 * Publishing resolves asset ids to URLs (+ alt text) so the snapshot is self-contained.
 * Returns the ids that could not be resolved instead of throwing.
 */
export function resolveKitMedia(
  kit: KitDocument,
  resolve: (assetId: string) => ResolvedAsset | undefined,
): { kit: KitDocument; missing: string[] } {
  const missing = new Set<string>()
  const resolved = mapKitMedia(kit, (ref) => {
    const asset = resolve(ref.assetId)
    if (!asset) {
      missing.add(ref.assetId)
      return ref
    }
    return {
      assetId: ref.assetId,
      url: asset.url,
      ...(asset.alt !== undefined
        ? { alt: asset.alt }
        : ref.alt !== undefined
          ? { alt: ref.alt }
          : {}),
    }
  })
  return { kit: resolved, missing: [...missing] }
}
