// GENERATED by scripts/sync-edge-entities.mjs from src/entities — do not edit here.
const TURKISH_ASCII: Record<string, string> = {
  ç: 'c',
  ğ: 'g',
  ı: 'i',
  ö: 'o',
  ş: 's',
  ü: 'u',
  â: 'a',
  î: 'i',
  û: 'u',
}

/**
 * URL-safe slug with Turkish casing rules: "IŞIK" → "isik", "İnsan" → "insan",
 * "Küçük Çiftçiler" → "kucuk-ciftciler".
 */
function toSlugChars(input: string) {
  return input
    .toLocaleLowerCase('tr')
    .replace(/[çğıöşüâîû]/g, (char) => TURKISH_ASCII[char] ?? '')
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
}

export function slugifyTr(input: string, maxLength = 60) {
  const slug = toSlugChars(input).replace(/^-+|-+$/g, '')
  return slug.slice(0, maxLength).replace(/-+$/, '')
}

/**
 * The same rules while someone types into an address field: a trailing "-" survives, so
 * "bahce-kiti" can be typed key by key. Finish with `slugifyTr` (on blur / submit).
 */
export function slugDraftTr(input: string, maxLength = 60) {
  return toSlugChars(input).replace(/^-+/, '').slice(0, maxLength)
}

/** Upper-case ASCII letters of a Turkish text: "Küçük Çiftçiler" → "KUCUK CIFTCILER". */
export function toAsciiUpper(input: string) {
  return slugifyTr(input, 200).replace(/-/g, ' ').toLocaleUpperCase('en')
}

/** Stable, deterministic string hash (FNV-1a, 32 bit) — for shuffles and demo data. */
export function hashString(input: string) {
  let hash = 0x811c9dc5
  for (let i = 0; i < input.length; i++) {
    hash ^= input.charCodeAt(i)
    hash = Math.imul(hash, 0x01000193)
  }
  return hash >>> 0
}

/** Small seeded PRNG (mulberry32). */
export function createRandom(seed: number) {
  let state = seed >>> 0
  return () => {
    state = (state + 0x6d2b79f5) >>> 0
    let t = state
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

/**
 * Deterministic shuffle that never returns the original order for 2+ distinct items
 * (a "sort these" puzzle that starts solved would be pointless).
 */
export function shuffleStable<T>(items: readonly T[], seed: string): T[] {
  if (items.length < 2) return [...items]
  const random = createRandom(hashString(seed))
  const result = [...items]
  for (let attempt = 0; attempt < 8; attempt++) {
    for (let i = result.length - 1; i > 0; i--) {
      const j = Math.floor(random() * (i + 1))
      const a = result[i]
      const b = result[j]
      if (a !== undefined && b !== undefined) {
        result[i] = b
        result[j] = a
      }
    }
    if (result.some((item, index) => item !== items[index])) return result
  }
  // Fall back to a rotation, which always differs for 2+ distinct items.
  return [...items.slice(1), ...items.slice(0, 1)]
}
